[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

# [[mgr.prepend_keymap]]
# on  = "y"
# run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[mgr]
prepend_keymap = [
    { on = "p", run = "plugin ucp paste notify", desc = "Paste" },
    { on = "y", run = "plugin ucp copy notify", desc = "Copy" }
]
